--- 
azs: 
  - ap-northeast-2a
cidr: 10.0.0.0/16
enable_nat_gateway: false
enable_vpn_gateway: false
name: "linuxstudy-${replace(basename(path.cwd), \\\"_\\\", \\\"-\\\")}"
public_subnets: 
  - 10.0.101.0/24
region: ap-northeast-2