---
serverA:
  name: "Server-A"
  ami: "ami-078fe19ee9f2d02b5" # Ubuntu Server 22.04 Clean 
  instance_type: "t3.micro"
  key_name: "kp220406"
  monitoring: true
  # vpc_security_group_ids:
  # subnet_id:
  private_ip: 10.0.101.11
  tags:
    Terraform: "true"
    Environment: "test"
# serverB:
#   name: "Server-B"
#   ami: "ami-0e9bfdb247cc8de84"
#   instance_type: "t3.micro"
#   key_name: "kp220406"
#   monitoring: true
#   # vpc_security_group_ids:
#   # subnet_id:
#   private_ip: 10.0.101.12
#   tags:
#     Terraform: "true"
#     Environment: "test"
client:
  name: "Client"
  ami: "ami-0e9bfdb247cc8de84" # Ubuntu Server 22.04 LTS (HVM), SSD Volume Type
  instance_type: "t3.micro"
  key_name: "kp220406"
  monitoring: true
  # vpc_security_group_ids:
  # subnet_id:
  private_ip: 10.0.101.21
  tags:
    Terraform: "true"
    Environment: "test"
winclient: 
  name: "WinClient"
  ami: "ami-03cbbbd628866a2b3"
  instance_type: "t3.micro"
  key_name: "kp220406"
  monitoring: true
  # vpc_security_group_ids:
  # subnet_id:
  private_ip: 10.0.101.22
  tags:
    Terraform: "true"
    Environment: "test"
