--- 
azs: 
  - ap-northeast-2a
cidr: 10.0.0.0/16
enable_nat_gateway: false
enable_vpn_gateway: false
name: "linuxstudy-vpc"
public_subnets: 
  - 10.0.101.0/24
private_subnets:
  - 10.0.1.0/24
  - 10.0.2.0/24
  - 10.0.3.0/24
region: ap-northeast-2